# -*- coding: utf-8 -*-
"""KLA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a_aIwr7i8VDTuqMAFt5WWiacQSnR-9Pc
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import json 

def rgb2gray(rgb):
    return np.dot(rgb[...,:3], [1,1,1])

 
f = open('input.json',) 
  
# returns JSON object as  
# a dictionary 
input = json.load(f) 
  
# Closing file 
f.close() 

img1 = plt.imread('wafer_image_1.png')
img2 = plt.imread('wafer_image_2.png')
img3 = plt.imread('wafer_image_3.png')
img4 = plt.imread('wafer_image_4.png')
img5 = plt.imread('wafer_image_5.png')
imggray1 = rgb2gray(img1)
imggray2 = rgb2gray(img2)
imggray3 = rgb2gray(img3)
imggray4 = rgb2gray(img4)
imggray5 = rgb2gray(img5)

data = []
# print(img1.shape)
# print(imggray1.shape)

for i in range(input['die']['height']):
  for j in range(input['die']['width']):
    row = []
    if(imggray1[i][j] - imggray2[i][j] != 0 and imggray1[i][j] - imggray3[i][j] != 0 ):
      row.append(1)
      row.append(j)
      row.append(input['die']['height']-i-1)
      data.append(row)
for i in range(input['die']['height']):
  for j in range(input['die']['width']):
    row = []
    if(imggray2[i][j] - imggray3[i][j] != 0 and imggray2[i][j] - imggray4[i][j] != 0  ):
      row.append(2)
      row.append(j)
      row.append(input['die']['height']-i-1)
      data.append(row)
for i in range(input['die']['height']):
  for j in range(input['die']['width']):
    row = []
    if(imggray3[i][j] - imggray4[i][j] != 0 and  imggray3[i][j] - imggray5[i][j] != 0 ):
      row.append(3)
      # row.append(input['die']['height']-i-1)
      row.append(j)
      row.append(input['die']['height']-i-1)
      data.append(row)
for i in range(input['die']['height']):
  for j in range(input['die']['width']):
    row = []
    if(imggray4[i][j] - imggray5[i][j] != 0  and imggray4[i][j] - imggray1[i][j] != 0 ):
      row.append(4)
      # row.append(input['die']['height']-i-1)
      row.append(j)
      row.append(input['die']['height']-i-1)
      data.append(row)
for i in range(input['die']['height']):
  for j in range(input['die']['width']):
    row = []
    if(imggray5[i][j] - imggray1[i][j] != 0 and imggray5[i][j] - imggray2[i][j] != 0 ):
      row.append(5)
      # row.append(input['die']['height']-i-1)
      row.append(j)
      row.append(input['die']['height']-i-1)
      data.append(row)
print(data)    

df = pd.DataFrame(data)      
df
df.to_csv('output_1.csv',index=False)
# for i in range(600):
#   for j in range(800):
#     print(imggray1[i][j])